language: python
python:
  - "2.7"
  - "3.7"

# command to install dependencies
install:
 - pip install -q Django==$DJANGO_VERSION djangorestframework==$DRF_VERSION

# setup different django versions
env:
  - DJANGO_VERSION=2.0 DRF_VERSION=3.9.2
  - DJANGO_VERSION=2.1 DRF_VERSION=3.9.2
  - DJANGO_VERSION=2.2 DRF_VERSION=3.9.2

# command to run tests
script:
  python ./test_samples/sample/manage.py test
