language: python
python:
  - "2.7"
  - "3.5"

# command to install dependencies
install:
 - pip install -q Django==$DJANGO_VERSION djangorestframework==3.3.1

# setup different django versions
env:
  - DJANGO_VERSION=1.9
#  - DJANGO_VERSION=1.10

# command to run tests
script:
  python ./tests/sample/manage.py test
