language: python
python:
  - "2.7"
  - "3.5"

# command to install dependencies
install:
 - pip install -q Django==$DJANGO_VERSION djangorestframework==$DRF_VERSION

# setup different django versions
env:
  - DJANGO_VERSION=1.9 DRF_VERSION=3.3.0
  - DJANGO_VERSION=1.9 DRF_VERSION=3.4.6
  - DJANGO_VERSION=1.10 DRF_VERSION=3.4.0
  - DJANGO_VERSION=1.10 DRF_VERSION=3.4.6

# command to run tests
script:
  python ./test_samples/sample/manage.py test
